Main branch Edge to Edge implementation
google-developer-training/basic-android-kotlin-compose-training-lunch-tray pull request #11
Opened 2023-08-02 01:35 UTC by the-scrambler

Merge pending codelab update.

2023-08-09 22:33 UTC, android-dev-lxl requested changes
- Please remove   `freeCompilerArgs += "-opt-in=androidx.compose.material3.ExperimentalMaterial3Api"`
- Upgrade Gradle to 8.1.0
- Upgrade Compose BOM version 
- Upgrade `kotlinCompilerExtensionVersion`
- Please upgrade other libs like `navigation-compose`

Not sure how we missed this in M3 and DSL upgrades

2023-08-11 21:59 UTC, android-dev-lxl approved these changes

2023-08-14 21:45 UTC, johnshea approved these changes
LGTM with some small changes.

- Correct `.padding()` issues noted in the file.
- Upgrade gradle wrapper to `8.2`

2023-08-14 21:45 UTC, johnshea commented on app/src/main/java/com/example/lunchtray/LunchTrayScreen.kt
> +                        .padding(innerPadding)
Combine the two `.padding()`  function calls into 1 or remove 1 depending on what you need.

2023-08-14 21:45 UTC, johnshea commented on app/src/main/java/com/example/lunchtray/LunchTrayScreen.kt
> +                        .padding(innerPadding)
Combine the two `.padding()`  function calls into 1 or remove 1 depending on what you need.

2023-08-14 21:45 UTC, johnshea commented on app/src/main/java/com/example/lunchtray/LunchTrayScreen.kt
> +                        .padding(innerPadding)
Combine the two `.padding()`  function calls into 1 or remove 1 depending on what you need.

2023-08-14 21:45 UTC, johnshea commented on app/src/main/java/com/example/lunchtray/LunchTrayScreen.kt
> +                        .padding(innerPadding)
Combine the two `.padding()`  function calls into 1 or remove 1 depending on what you need.

2023-08-14 21:45 UTC, johnshea commented on app/src/main/java/com/example/lunchtray/LunchTrayScreen.kt
> +                        .padding(innerPadding)
Combine the two `.padding()`  function calls into 1 or remove 1 depending on what you need.

2023-08-29 20:22 UTC, merged